### PR TITLE
Update pytest-base-url to version 2.0.0

### PR DESCRIPTION
**Pull request by rxm7706**
Aligned to Grayskull 
Requirements updated from https://github.com/pytest-dev/pytest-base-url/blob/master/pyproject.toml

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
Hi @birdsarah @davehunt could you review and merge please.

**Comment by davehunt** [comment]
@nicoddemus are you able to help here? I haven't been involved with this plugin for some time, and I suspect the same is true for @birdsarah. /cc @BeyondEvil

**Comment by nicoddemus** [comment]
Sure be glad to help, can you please add me to the maintainers in `meta.yaml`?

**Comment by davehunt** [comment]
> Sure be glad to help, can you please add me to the maintainers in `meta.yaml`?

Thanks, I have added you.

**Review by nicoddemus — APPROVED** [review]

**Pull request merged**
